"""
Echidna / Foundry fuzzing harness generator.

Given a Solidity contract, this module generates a fuzz-testing harness
with property-based invariants that Echidna or Foundry can run.

Derived from:
  - Chapter 06: Fuzzing Solidity Smart Contracts with Echidna
"""

import re
from pathlib import Path


def generate_fuzz_harness(source: str, filepath: str) -> str:
    """Generate a fuzz harness contract for the given Solidity source."""
    contracts = _extract_contracts(source)
    if not contracts:
        return "// No contracts found to generate fuzz harness for.\n"

    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Fuzz harness auto-generated by Solidity Audit Agent",
        f"// Source: {filepath}",
        "//",
        "// Usage with Echidna:",
        f"//   echidna {Path(filepath).name}.harness.sol --contract {contracts[0]['name']}Harness",
        "//",
        "// Usage with Foundry:",
        "//   forge test --match-path **/*.harness.sol",
        "",
        'pragma solidity ^0.8.0;',
        "",
    ]

    for c in contracts:
        harness = _generate_harness(c, source)
        lines.append(harness)

    return "\n".join(lines)


def _extract_contracts(source: str) -> list[dict]:
    """Return list of {name, body_start, body_end} for each contract."""
    results = []
    pattern = re.compile(r'contract\s+(\w+)\s*(?:is\s+[^{]*)?\{')
    for m in pattern.finditer(source):
        name = m.group(1)
        brace = m.start(0) + source[m.start(0):].find('{')
        depth, pos = 1, brace + 1
        while pos < len(source) and depth > 0:
            if source[pos] == '{': depth += 1
            elif source[pos] == '}': depth -= 1
            pos += 1
        if depth == 0:
            results.append({
                'name': name,
                'body_start': brace,
                'body_end': pos,
            })
    return results


def _generate_harness(contract: dict, source: str) -> str:
    name = contract['name']
    body = source[contract['body_start']:contract['body_end']]

    # Identify state variables
    state_vars = re.findall(
        r'(mapping|address|uint\d*|bool|string|bytes\d*)\s+(public\s+)?(\w+)',
        body,
    )

    # Identify public/external functions
    funcs = list(re.finditer(
        r'function\s+(\w+)\s*\([^)]*\)\s*(?:public|external)[^\{]*\{',
        source[contract['body_start']:contract['body_end']],
    ))

    # Identify view functions (potential invariants)
    view_funcs = [
        m for m in funcs
        if re.search(r'\bview\b', m.group(0))
    ]

    # Identify state-changing functions
    mut_funcs = [
        m for m in funcs
        if not re.search(r'\bview\b|\bpure\b', m.group(0))
    ]

    harness_lines = [
        f"// === {name} Fuzz Harness ===",
        "",
        f"import \"../{name}.sol\";" if name else "",
        "",
        f"contract {name}Harness is {name} {{",
        "    // --- Deployed actor addresses for fuzzing ---",
        "    address internal constant ACTOR_1 = address(0x1000);",
        "    address internal constant ACTOR_2 = address(0x2000);",
        "    address internal constant ACTOR_3 = address(0x3000);",
        "",
    ]

    # Setup function for Echidna
    harness_lines.extend([
        "    // --- Echidna setup (called before each fuzz run) ---",
        "    constructor() {",
    ])

    # Find constructor in the contract
    ctor = re.search(r'constructor\s*\([^)]*\)', body)
    if not ctor:
        harness_lines.append("        // Default: no constructor needed")
    harness_lines.append("    }")
    harness_lines.append("")

    # --- Entity handler setup for Foundry-style fuzzing ---
    if mut_funcs:
        harness_lines.extend([
            "    // --- Handler functions (Foundry-style) ---",
            "    // These call the target contract's functions with random inputs.",
            "    // In Foundry: fuzz runs `function testFuzz_*` with random parameters.",
            "",
        ])

        for mf in mut_funcs:
            f_name = mf.group(1)
            params = mf.group(0)
            # Extract parameter declarations
            param_list = re.search(r'\(([^)]*)\)', params)
            param_str = param_list.group(1) if param_list else ""

            harness_lines.extend([
                f"    /// @notice Fuzz handler for `{f_name}`",
                f"    function call_{f_name}({param_str}) public {{",
            ])

            # Try to delegate to the real function
            param_names = re.findall(r'(?:calldata|memory|)\s*(\w+)\s*(?:,|\))', param_str)
            call_args = ", ".join(param_names) if param_names else ""

            harness_lines.extend([
                f"        this.{f_name}({call_args});",
                "    }",
                "",
            ])

    # --- Invariant assertions ---
    if view_funcs:
        harness_lines.extend([
            "    // --- Echidna invariant checks ---",
            "    // These must always hold; Echidna raises a finding if they fail.",
            "",
        ])

        for vf in view_funcs:
            v_name = vf.group(1)
            if re.search(r'(price|rate|balance|supply|total|count|length)', v_name, re.I):
                harness_lines.extend([
                    f"    /// @notice Invariant: {v_name} should never revert",
                    f"    function echidna_{v_name}_stable() public view returns (bool) {{",
                    f"        // Warning: this function may need access control to avoid reentrancy",
                    f"        // during other fuzz operations.",
                    f"        (bool success, ) = address(this).staticcall(",
                    f"            abi.encodeWithSignature(\"{v_name}()\")",
                    f"        );",
                    f"        return success;",
                    f"    }}",
                    "",
                ])

    # Generic invariants
    harness_lines.extend([
        "    // --- Generic Echidna invariants ---",
        "",
        "    /// @notice Invariant: contract should always have non-negative balance (ETH)",
        "    function echidna_eth_balance() public view returns (bool) {",
        "        return address(this).balance >= 0;",
        "    }",
        "",
    ])

    harness_lines.append("}")
    harness_lines.append("")

    return "\n".join(harness_lines)


# Exposed for the main entry point
__all__ = ["generate_fuzz_harness"]
